export const testimonials = [
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-gray-300",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-yellow-300",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-gray-300",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-yellow-300",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-blue-300",
    },
   
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-blue-300",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-yellow-300",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-gray-200",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-yellowgreen-300",
    },
    {
      text: "The bootcamp and the hands-on projects gave me the skills and confidence to make the leap into Data Science. I appreciated the structured course content, the expert instructors, and the collaborative learning environment. Highly recommend this bootcamp to anyone looking to pivot into tech!",
      name: "Eugenia Mazzaferro",
      batch: "Nod Coding BC#2 2023",
      role: "Data Scientist @King",
      bgColor: "bg-blue-300",
    },
    {
      text: "The bootcamp was very high-paced, and I liked how the teachers kept on challenging me to deepen my understanding of technical concepts. The bootcamp allowed me to pivot to a highly technical and analytical role, exactly what I wanted.",
      name: "Gustavo Lopez",
      batch: "Coding BC#1 2023",
      role: "Data Analyst @TechCorp",
      bgColor: "bg-yellow-300",
    },
    {
      text: "Besides all the good moments with teachers and students, the bootcamp equipped me with practical skills that helped me start a new career in tech where I'm now working in a development team building an AI product for my company. I continue to use what I learnt in the bootcamp on an everyday basis.",
      name: "Nicole Evans",
      batch: "Coding End 2023",
      role: "Developer @AI Innovations",
      bgColor: "bg-green-300",
    },
  ];